services:
  # Backend API Service
  - type: web
    name: shedula-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://shedula-frontend.onrender.com
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: shedula-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://shedula-api.onrender.com/api
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 